"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production settings!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party packages
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    
    # myAiPA apps
    'accounts',
    'tasks',
    'scheduler',
    'briefing',
    'ai_service',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'











# myAiPA uses a custom User model defined in accounts/models.py
# instead of Django's default User model.
# This gives us full control to add myAiPA-specific fields
# like timezone, myAiPA_name, briefing_time and streak_count.
# IMPORTANT: This must always be set before the very first
# migration otherwise Django will not recognise our custom User
# and the entire authentication system will break.
AUTH_USER_MODEL = 'accounts.User'






# =============================================================
# REST FRAMEWORK CONFIGURATION
# Controls how myAiPA's API handles authentication,
# permissions and responses globally.
# =============================================================

REST_FRAMEWORK = {

    # Default authentication method for all endpoints.
    # JWTAuthentication means every request must send
    # a valid JWT token in the Authorization header.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # Default permission for all endpoints.
    # IsAuthenticated means every endpoint is protected
    # by default — no token, no access.
    # Individual views can override this if needed.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    # Consistent error response format across
    # all myAiPA API endpoints.
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}


# =============================================================
# JWT CONFIGURATION
# Controls how myAiPA's JWT tokens behave.
# =============================================================

from datetime import timedelta

SIMPLE_JWT = {

    # Access token expires in 15 minutes.
    # Short lived for security — if stolen,
    # attacker has only 15 minutes.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),

    # Refresh token expires in 7 days.
    # Used only to get a new access token.
    # Longer lived for user convenience.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # When a refresh token is used, give the user
    # a brand new refresh token automatically.
    # Keeps them logged in without re-entering password.
    'ROTATE_REFRESH_TOKENS': True,

    # When a new refresh token is issued, blacklist
    # the old one immediately so it cannot be reused.
    # Prevents token theft attacks.
    'BLACKLIST_AFTER_ROTATION': True,

    # The algorithm used to sign tokens.
    # HS256 is the industry standard.
    'ALGORITHM': 'HS256',

    # The header type sent with every request.
    # Authorization: Bearer <token>
    'AUTH_HEADER_TYPES': ('Bearer',),

    # Which field from the User model identifies
    # the user inside the token payload.
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}



# =============================================================
# CORS CONFIGURATION
# Controls which frontend domains can call myAiPA's API.
# Without this — browser blocks all cross-origin requests.
# =============================================================

# In development — allow React local server
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://my-ai-pa.vercel.app",
    "https://my-ai-hdvnwha7t-lakshya-pandeys-projects.vercel.app",
]
# Allow cookies and auth headers to be sent
CORS_ALLOW_CREDENTIALS = True