# Generated by Django 6.0.5 on 2026-05-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already registered with myAiPA.'}, max_length=254, unique=True),
        ),
    ]
